### ISSUE TITLE
.autoNumeric('getSettings').rawValue has old value on input event when pasting

### ISSUE THREAD

**Issue by rhyek** [BobKnothe/autoNumeric#251]
I'm working on a Vue.js component that utilizes this plugin and am mostly done working out the quirks when syncing data between the input and the component's state. You can check it out [here](https://jsfiddle.net/rhyek/vuxgtgx0/). It has a little hack by way of handling the `paste` event to deal with the issue I'm experiencing.

I think the final piece is solving an issue I'm having when pasting values to the input. I'm using the `input` event triggered on the input (autoNumeric 2.0) to process the synchronization. It works great when typing, but when I try to paste I get the behavior mentioned in the title. You can test it for yourself [here](https://jsfiddle.net/rhyek/uxncmv9s/).

Is there something different I should be trying? Thank you.

**Comment by BobKnothe** [comment]
How are you pasteing "ctrl" & "v" or mouse?

**Comment by rhyek** [comment]
Both. BUT, now that you mention that, if you look at my Vue component [here](https://jsfiddle.net/rhyek/vuxgtgx0/), there's some additional strange behavior when pasting. It probably has to do with the way I'm handling the paste event.

You can see that after pasting, both the raw and formatted values are shown. When using the keyboard, it only happens for a split second (maybe updated on `keyup`?), but when using click, they both remain.

http://imgur.com/a/lJoCv

**Comment by rhyek** [comment]
@BobKnothe:

I think I've done pretty much all I can with the component, but the issues with pasting remain:

- When pasting, the input event is triggered, but doing `.autoNumeric('get')` gives the old value so workarounds are needed.
- The most obvious workaround is attaching a `paste` event handler on the input and capturing the raw text there and try to sync with it.
- If I paste an invalid value (can be any random text or even an already formatted number like '$ 123,344,233.00'), this will break the workaround because I am trying to sync with the raw pasted text instead of the `rawValue` **autoNumeric** normally produces (not updated yet on the `paste` or `input` handlers).

Basically, what is needed is for the `input` event **autoNumeric** fires to guarantee that when you do `.autoNumeric('get')` you get an updated raw value. This is already true when *typing* in a number. The event should also be fired only when a **new** and most importantly a **VALID** `rawValue` that represents the current text in the input is available (eg, the last update to the input actually produced a valid number).

This could also mean producing a new event specific for this purpose. Something like 'autoNumeric.formatted'.

Without this guarantee, I'm afraid it is *quite* difficult to use the plugin reliably with something like **Vue.js**.

Alternatively, @AlexandreBonneau asks for an "unformat" method in issue #245. This could help when using the `paste` workaround. In his [codepen](http://codepen.io/AnotherLinuxUser/pen/VmwvOK?editors=1010) posted in issue #247, he uses a custom method called `unformatEuroNumber`. This is kinda the right approach, but it is too specific for his use-case. A proper "unformat" method should take into account the current **autoNumeric** element's settings to know the correct `aSep` character to strip out, for example. I'm not sure if this is even practical from a development standpoint, to be honest.

**Comment by rhyek** [comment]
FYI, here is an updated [fiddle](https://jsfiddle.net/rhyek/vuxgtgx0/22/) that showcases my component.

**Comment by BobKnothe** [comment]
I have been working on a major update on 2.0 and I found this this behavior. Going back over my changes to see how i addressed this.

Hopefully I can post today.

**Comment by BobKnothe** [comment]
@rhyek,

I added support for context menu pasting event that I believe will address your issue.

You may also want to see how I change the focusin event and dealing with the rawValue.

Can you please test the changing and close the issue if you are satisfied.

Thanks for you help.

Bob

**Comment by rhyek** [comment]
@BobKnothe, hi:

The issue still remains. Here are my findings:
- When pasting using context menu:
 - if there is NO text previously present on the input, when pasting a RAW number (9999), `.autoNumeric('get')` shows the updated RAW value.
 - if there IS text previously, when pasting a RAW number `.autoNumeric('get')` shows the OLD value.
 - if there is NO text previously, when pasting a FORMATTED number (9,999), `.autoNUmeric('get')` shows an updated FORMATTED value. It should be raw.
 - if there IS text previously, when pasting a FORMATTED number, `('get')` shows the OLD value.

- When pasting using the keyboard:
 - if there is NO text previously present on the input, when pasting a RAW number (9999), `.autoNumeric('get')` shows the updated RAW value.
 - if there IS text previously, when pasting a RAW number `.autoNumeric('get')` shows the OLD value.
 - if there is NO text previously, when pasting a FORMATTED number (9,999), `.autoNUmeric('get')` shows an updated FORMATTED value. It should be raw.
 - if there IS text previously, when pasting a FORMATTED number, `('get')` shows the OLD value.

So it appears behavior is consisted between both methods of pasting. That's great.

What changed:
- Previously, when pasting using the context menu, I think the number wouldn't get formatted until you focused out of the input. Now it gets formatted immediately. This is good.

Here is a link to [codepen](https://codepen.io/rhyek/pen/oYxzqV?editors=1010). FYI, I'm using rawgit dev to link to your 2.0 beta file directly on github.

**Comment by rhyek** [comment]
Just to reiterate, as you can see in my code, I'm relying on the `input` event to catch any updates. This is how you want it to work if you want to utilize the library with modern JS frameworks like Vue. The codepen is just jQuery though, no Vue.

**Comment by rhyek** [comment]
@BobKnothe, I made a small change to your `paste` handler that allows me to get the pasted text without relying on `setTimeout`. Now, when I paste using the context menu, `.autoNumeric('get')` has the updated RAW value. The problem is that for some reason I see the following behavior:

1)
- Paste 8888.
- `.autoNumeric('get')` returns 8888.00 (great)
- input shows 8,888.008888.00 (formatted value plus rawValue).

2)
- Paste 8,888.
- `.autoNumeric('get')` returns 8888.00 (great)
- input shows 8,888.008,888 (formatted value plus pasted value).

You can look at it in my [codepen](https://codepen.io/rhyek/pen/oYxzqV?editors=1010) which now points to my forked project.

The [commit](https://github.com/rhyek/autoNumeric/commit/40d7d396d61a6ee3c67f24ce42703f3a8ca850c3).

Also, would it be possible to handle `paste` events this way for both pasting with context menu and keyboard to maintain consistency? I think the issue mentioned in this comment can be fixed and then handling both scenarios with your `paste` handler would solve this whole issue once and for all.

**Comment by rhyek** [comment]
@BobKnothe, I fixed it! Here's the code:
```js
$this.on("paste", function (e) {
    holder = getHolder($this);
    var $settings = holder.settingsClone;
    if ($settings.mouseUp) {
        var pastedValue = autoStrip(e.originalEvent.clipboardData.getData('text/plain'), $settings);
        $this.autoNumeric("set", pastedValue);
        e.preventDefault();
        $this.trigger('input');
    }
});
```

Now everything works perfectly when pasting using the mouse. All that's left is to use this handler for pasting with keyboard.

**Comment by rhyek** [comment]
@BobKnothe, even better:
```js
$this.on("paste", function (e) {
    holder = getHolder($this);
    var $settings = holder.settingsClone;
    if ($settings.mouseUp) {
        var pastedValue = autoStrip(e.originalEvent.clipboardData.getData('text/plain'), $settings);
        if (pastedValue !== '') {
            $this.autoNumeric("set", pastedValue);
            e.preventDefault();
            $this.trigger('input');
        }
    }
});
```
Now, if you paste something like "sdsddsd", no `input` event is raised. Perfect.

**Comment by rhyek** [comment]
@BobKnothe, sorry, these are a lot of updates.
```js
$this.on("paste", function (e) {
    holder = getHolder($this);
    var $settings = holder.settingsClone;
    if ($settings.mouseUp) {
        e.preventDefault();
        var pastedValue = autoStrip(e.originalEvent.clipboardData.getData('text/plain'), $settings);
        if (!isNaN(pastedValue)) {
            $this.autoNumeric("set", pastedValue);
            $this.trigger('input');
        }
    }
});
```
This is working best for me because if you paste something invalid, the input does not get updated either and if you paste something invalid that contains at least a period, for example, `autoStrip` will return '.'. So it's best to use `isNan` instead of `pastedValue !== ''`;

**Comment by rhyek** [comment]
Ok, well, apparently `isNaN('') === false`. We need to use both.
```js
$this.on("paste", function (e) {
    holder = getHolder($this);
    var $settings = holder.settingsClone;
    if ($settings.mouseUp) {
        e.preventDefault();
        var pastedValue = autoStrip(e.originalEvent.clipboardData.getData('text/plain'), $settings);
        if (pastedValue !== '' && !isNaN(pastedValue)) {
            $this.autoNumeric("set", pastedValue);
            $this.trigger('input');
        }
    }
});
```

**Comment by rhyek** [comment]
Yes, that last update is perfect. Now all we need is to have this handler also handle keyboard pastes. Is this possible?

**Comment by BobKnothe** [comment]
@rhyek,

Thank you for the code - small issue thought.

Ir works great if you are pasting into an empty input. However if the user is inserting paste value between numbers you only capture the clipboard value.

**Comment by rhyek** [comment]
Hm, true. Ok. It may be possible to use `setTimeout` then and still do it this way. Let me try that out.

**Comment by BobKnothe** [comment]
Also if the user is pasting properly formatted string - that is why i used the autoStrip function.

**Comment by rhyek** [comment]
Yes, with my change I'm still using `autoStrip()`. Pasting formatted numbers will work. I'm looking into the issue about pasting a number in the middle of present text.

**Comment by rhyek** [comment]
@BobKnothe, I have made a second pull request (#253) that now lets you paste in the middle of text.

This change also handles pastes with both keyboard and mouse with the same handler.

**Comment by rhyek** [comment]
@BobKnothe, thank you so much for your help.
